/*
 * Copyright 2017 Renato Utsch
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef COMPNAT_TP1_STATISTICS_HPP
#define COMPNAT_TP1_STATISTICS_HPP

#include <string>
#include <vector>

#include "representation.hpp"

namespace stats {

/**
 * Calculates the fitness of an individual given a set of input data.
 * This is implemented as the Root-mean-square deviation.
 * @param individual The individual used when calculating the fitness.
 * @param size The size of the individual.
 * @param dataset Dataset to use to calculate the fitness.
 * @return A pair of the fitness and the RMSE.
 */
double fitness(const repr::Node &individual, const repr::Dataset &dataset);

/**
 * Calculates the fitness for all population and returns it in a vector.
 * This is implemented as the Root-mean-square deviation.
 * @param pool Thread pool.
 * @param population The population used when calculating the fitness.
 * @param sizes The size of each individual in the population.
 * @param dataset The dataset used to calculate the fitness.
 * @return Vector of fitness.
 */
std::vector<double> fitness(const std::vector<repr::Node> &population,
                            const repr::Dataset &dataset);

/**
 * Calculates the size for all the population.
 */
std::vector<size_t> sizes(const std::vector<repr::Node> &population);

/// Per-generation improvement stats.
struct ImprovementMetadata {
  /// Vector containing pair of individual index and average fitness of the
  /// parents for all individuals generated through crossover.
  std::vector<std::pair<size_t, double>> crossoverAvgParentFitness;

  /// Vector containing pair of individual index and fitness of the parent for
  /// all individuals generated through mutation.
  std::vector<std::pair<size_t, double>> mutationParentFitness;
};

/**
 * Stores the statistics of each generation.
 */
struct Statistics {
  /// Index of the best individual in the generation.
  size_t best;

  /// Fitness of the best individual.
  double bestFitness;

  /// Size of the best individual.
  size_t bestSize;

  /// String representation of the best individual.
  std::string bestStr;

  /// Index of the worst individual in the generation.
  size_t worst;

  /// Fitness of the worst individual.
  double worstFitness;

  /// Size of the worst individual.
  size_t worstSize;

  /// Average fitness of the generation.
  double avgFitness;

  /// Average individual size.
  size_t avgSize;

  /// Number of repeated individuals in the generation.
  size_t numRepeated;

  /// Number of individuals generated by crossover better than their parents.
  int numCrossBetter;

  /// Number of individuals generated by crossover worse than their parents.
  int numCrossWorse;

  /// Number of individuals generated by mutation better than their parent.
  int numMutBetter;

  /// Number of individuals generated by mutation worse than their parent.
  int numMutWorse;

  Statistics(const std::string &statsName,
             const std::vector<repr::Node> &population,
             const std::vector<double> &fitnesses,
             const std::vector<size_t> &sizes,
             const ImprovementMetadata &metadata = {});

private:
  /// best, worst, avg.
  void calcFitnessAndSizeStats_(const std::vector<repr::Node> &population,
                                const std::vector<double> &fitnesses,
                                const std::vector<size_t> &sizes);

  /// numRepeated.
  void calcRepeatedIndividuals_(const std::vector<double> &fitnesses);

  // num[Crossover/Mutation]Better, num[Crossover/Mutation]Worse.
  void calcImprovementStats_(const std::vector<double> &fitnesses,
                             const ImprovementMetadata &metadata);

  void calcFitnessImprovement_(
      const std::vector<std::pair<size_t, double>> &avgParentFitnesses,
      const std::vector<double> &fitnesses, int &better, int &worse);

  void printStats_(const std::string &statsName);
};

/**
 * Salves the execution results to the file specified in params.
 */
void saveResults(const repr::Params &params,
                 const std::vector<std::vector<Statistics>> &allTrainStats,
                 const std::vector<std::vector<Statistics>> &allTestStats);

} // namespace stats

#endif // !COMPNAT_TP1_STATISTICS_HPP
